Repository tonbo-io/tonbo, pull requests merged in 2024-08, with the labels that each got.

#34 Feat/database recover 1
  Cargo.toml
  src/compaction/mod.rs
  src/fs/mod.rs
  src/fs/tokio.rs
  src/inmem/mutable.rs
  src/lib.rs
  src/option.rs
  src/stream/merge.rs
  src/timestamp/mod.rs
  src/wal/mod.rs
Labels: enhancement

#35 refactor: `transaction_ts` -> `Version::transaction` & `VersionSet::t…
  src/compaction/mod.rs
  src/inmem/mutable.rs
  src/lib.rs
  src/transaction.rs
  src/version/mod.rs
  src/version/set.rs
Labels: enhancement

#37 docs: add `Introduction`
  README.md
Labels: documentation

#41 chore: `dbg!` -> `assert!`
  src/ondisk/sstable.rs
  src/stream/merge.rs
  src/stream/package.rs
  src/transaction.rs
Labels: invalid

#47 feat: impl `Key` for num
  src/record/mod.rs
  src/record/num.rs
  src/tonbo_marco/src/keys.rs
  src/tonbo_marco/src/lib.rs
Labels: invalid

#49 fix: incorrect option encoding size
  examples/declare.rs
  src/serdes/option.rs
Labels: bug

#60 fix: major compaction does not trigger when there is no intersecting …
  src/compaction/mod.rs
  src/lib.rs
  src/option.rs
Labels: bug

#67 chore: configure WriterProperties
  src/ondisk/scan.rs
  src/ondisk/sstable.rs
  src/option.rs
Labels: invalid

#106 fix: add ts filter on MergeStream
  src/compaction/mod.rs
  src/lib.rs
  src/stream/merge.rs
  src/stream/package.rs
  src/transaction.rs
  src/trigger.rs
Labels: bug

#114 feat: add flush compaction task with oneshot notification
  src/compaction/mod.rs
  src/lib.rs
  src/transaction.rs
Labels: enhancement
