Repository tonbo-io/tonbo, pull requests merged in 2024-09, with the labels that each got.

#119 fix: scan is able to be a sync method
  benches/common.rs
  examples/datafusion.rs
  examples/declare.rs
  src/lib.rs
  src/transaction.rs
Labels: enhancement

#125 chore: improve timestamp test
  src/timestamp/timestamped.rs
Labels: XS - Tiny

#130 fix: cleaner recover clean
  src/fs/tokio_fs.rs
  src/version/cleaner.rs
  src/version/set.rs
Labels: bug, S - Small

#132 point query optimization
  src/inmem/immutable.rs
  src/inmem/mutable.rs
  src/lib.rs
  src/transaction.rs
Labels: enhancement, S - Small

#122 chore: avoid `transaction_ts` from incrementing every time
  src/compaction/mod.rs
  src/lib.rs
  src/transaction.rs
  src/version/mod.rs
  src/version/set.rs
  tests/data_integrity.rs
Labels: enhancement, S - Small

#131 feat: support VersionLog Snapshot
  src/fs/mod.rs
  src/fs/tokio_fs.rs
  src/lib.rs
  src/option.rs
  src/version/edit.rs
  src/version/mod.rs
  src/version/set.rs
Labels: enhancement, S - Small

#136 fix: resolve merge & `test::transaction_get`
  src/transaction.rs
  src/version/mod.rs
Labels: bug, XS - Tiny

#124 feat: added `MemProjection` for projecting `TransactionScan` and `MutableScan`
  src/lib.rs
  src/record/mod.rs
  src/record/str.rs
  src/stream/mem_projection.rs
  src/stream/mod.rs
  src/transaction.rs
  tonbo_macros/src/lib.rs
Labels: enhancement, S - Small

#139 fix level scope index
  src/compaction/mod.rs
Labels: bug

#141 impl new derive macro to replace attribute macro
  .github/workflows/ci.yml
  README.md
  benches/common.rs
  benches/criterion/writes.rs
  examples/datafusion.rs
  examples/declare.rs
  src/lib.rs
  src/record/internal.rs
  tests/data_integrity.rs
  tests/fail/01-missing-primary-key.rs
  tests/fail/01-missing-primary-key.stderr
  tests/macros_correctness.rs
  tests/success/01-simple-record.rs
  tonbo_macros/Cargo.toml
  tonbo_macros/src/data_type.rs
  tonbo_macros/src/keys.rs
  tonbo_macros/src/lib.rs
  tonbo_macros/src/record.rs
  tonbo_macros/src/schema_model.rs
  tonbo_macros/src/utils/ident_generator.rs
  tonbo_macros/src/utils/mod.rs
Labels: enhancement, L - Large

#143 fix oneshot channel dropped while mutable is empty
  src/compaction/mod.rs
Labels: bug

#148 ci: only run benchmark in pr event
  .github/workflows/ci.yml
Labels: bug, XS - Tiny

#144 perf: `check_then_compaction` write lock optimization
  src/compaction/mod.rs
  src/lib.rs
Labels: enhancement, XS - Tiny

#147 feat: support DataType `bytes::Bytes`
  Cargo.toml
  examples/declare.rs
  src/serdes/bytes.rs
  src/serdes/mod.rs
  tonbo_macros/src/data_type.rs
  tonbo_macros/src/record.rs
Labels: enhancement, S - Small

#145 fix: clear invalid `version_log`
  src/version/edit.rs
  src/version/set.rs
Labels: bug, S - Small

#155 drop lock before flush
  src/lib.rs
Labels: bug

#156 fix level slice ordered
  src/version/set.rs
Labels: bug

#159 ci: add permissions for benchmark action
  .github/workflows/ci.yml
Labels: bug

#168 fix point query at sst
  benches/common.rs
  src/lib.rs
  src/ondisk/sstable.rs
  src/record/str.rs
Labels: bug, XS - Tiny

#174 fix: #172
  examples/datafusion.rs
Labels: bug
